---
- name: "Move Window PATH environment to bottom"
  win_path:
    elements:
      - '%SYSTEMROOT%'
      - '%SYSTEMROOT%\system32'
      - '%SYSTEMROOT%\System32\Wbem'
      - '%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\'
      - '%SYSTEMROOT%\System32\OpenSSH\'
      - 'C:\WINDOWS'
      - 'C:\WINDOWS\system32'
      - 'C:\WINDOWS\System32\Wbem'
      - 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\'
      - 'C:\WINDOWS\System32\OpenSSH\'
      - 'C:\Program Files\Git\usr\bin'
    state: absent

- name: "Set PATH environment variable"
  win_path:
    elements:
      # - 'C:\Program Files\curl\bin'
      - 'C:\Program Files\Git\cmd'
      - 'C:\TCC'
      - 'C:\TCC\itc2'
      - '%SYSTEMROOT%'
      - '%SYSTEMROOT%\system32'
      - '%SYSTEMROOT%\System32\Wbem'
      - '%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\'
      - '%SYSTEMROOT%\System32\OpenSSH\'
      - 'C:\Program Files\Git\usr\bin'

# - name: "Set other environment variable"
#   win_environment:
#     name: "{{ item.name }}"
#     value: "{{ item.value }}"
#     level: "{{ item.level }}"
#   with_items:
#     - { name: "OneDrive", value: "%USERPROFILE%\\OneDrive", level: user}
#     - { name: "ARMLMD_LICENSE_FILE", value: "8224@rb-lic-armlmd-ccda-video.de.bosch.com", level: machine} # ?
#     - { name: "PSModulePath", value: "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", level: machine}
#     - { name: "TERM", value: "dumb", level: machine}  # ?
#     - { name: "TELELOGIC_LICENSE_FILE", value: "1706@rb-lic-telelogic.de.bosch.com", level: machine }

- name: "Reboot"
  win_reboot:
