---
- debug:
    msg: "This is COVERITY"

- include_role:
    name: "had.win_tcc"

- name: "COVERITY - Update and install via ITC2"
  win_command: "{{ item }}"
  with_items:
    - updateITC2.exe
    - itc2 install RadarGen5CI:3.3.14
    - itc2 install ACA:0.5.5

- name: "COVERITY - Install"
  win_shell: "_install_TCC_coverity.bat 12"
  args:
    chdir: "{{ jenkins_home }}\\ws\\commonrepo@1\\repo\\cust\\common\\tools\\sca_tools_package\\scripts\\tcc"
    executable: cmd.exe

- name: "COVERITY - Add 'tee' command to PATH"
  win_path:
    elements:
      - 'C:\Program Files\Git\usr\bin'
