---
- debug:
    msg: "This is ECU_TARGET"

- name: "ECU_TARGET - Enable DelayedExpansion"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Command Processor
    name: DelayedExpansion
    data: 1
    type: dword

- name: "ECU_TARGET - Update and install via ITC2"
  win_command: "{{ item }}"
  with_items:
    - updateITC2.exe
    - itc2 install ACA:0.5.5
