---
- debug:
    msg: "This is SW_TEST"

- include_role:
    name: had.win_vs2019

- name: "SW_TEST - Update and install via ITC2"
  win_command: "{{ item }}"
  with_items:
    - updateITC2.exe
    - itc2 install IF:VAG-basedOnBtc610
    - itc2 install OD:12.2
