---
- name: "Add .ssh directory"
  file:
    path: "/home/{{ git_user }}/.ssh"
    state: directory

- name: "Add private key for user {{ git_user }}"
  template:
    dest: "/home/{{ git_user }}/.ssh/id_rsa"
    src: id_rsa.j2
    mode: '0600'

- name: "Add private key for user {{ git_user }}"
  template:
    dest: "/home/{{ git_user }}/.ssh/known_hosts"
    src: known_hosts.j2
